insert into riddles values(1, 'I get wet when drying. I get dirty when wiping. What am I?','Towel');
insert into riddles values(2, 'I can be cracked, made, told, and played. What am I?','Joke');
insert into riddles values(3, 'I wiggled and cannot see, sometimes underground and sometimes on a tree. I really don’t want to be on a hook, and I become a person when combined with a book?','Worm');
insert into riddles values(4, 'I like to twirl my body but keep my head up high. After I go in, everything becomes tight. What am I?','Screw');
insert into riddles values(5, 'I am gentle enough to soothe your skin, light enough to fly in the sky, strong enough to crack rocks. What am I?','Water');
insert into riddles values(6, 'I can fly but have no wings. I can cry but I have no eyes. Wherever I go, darkness follows me. What am I?','Cloud');
insert into riddles values(7, 'Although I may have eyes I cannot see. I have a round brown face with lots of acne. What am I?','Potato');
insert into riddles values(8, 'I eat, I live. I breathe, I live. I drink, I die. What am I?','Fire');
insert into riddles values(9, 'I am a seed with three letters in my name. Take away the last two and I still sound the same. What am I?','Pea');
insert into riddles values(10, 'I am lighter than air but a hundred people cannot lift me. Careful, I am fragile. What am I?','Bubble');
insert into riddles values(11, 'Although glory but not at my best. Power will fall to me finally, when the man made me is dead. What am I?','Prince');
insert into riddles values(12, 'I am the type of room you can not enter or leave. Raise from the ground below, I could be poisonous or a delicious trea. What am I?','Mushroom');
insert into riddles values(13, 'The more you take of me, the more you leave behind. What am I?','Footstep');
insert into riddles values(14, 'I go up and never come down no matter how hard you wish. As I get higher, more wrinkles crawl on to the face. What am I?','Age');
insert into riddles values(15, 'I can be long or short. I can be grown or bought. I can be painted or left bare. My tip can be round or square. (one word) What am I?','Fingernails');
insert into riddles values(16, 'I have a neck and no head, two arms but no hands. I’m with you to school, I’m with you to work. What am I?','Shirt');
insert into riddles values(17, 'I shrink smaller every time I take a bath. What am I?','Soap');
insert into riddles values(18, 'I am heavy forward, but backward I’m not. What am I?','Ton');
insert into riddles values(19, 'I wear a green jacket on the outside, white jacket as a second layer, and a red jacket inside. I am pregnant with a lot of babies. What am I?','Watermelon');
insert into riddles values(20, 'I am good at concealing what’s real and hide what’s true. Sometime, I bring out the courage in you! What am I?','Makeup');
insert into riddles values(21, 'I have a face but no eyes, hands but no arms. What am I?','Clock');
insert into riddles values(22, 'With three eyes and a black as night, I frequently knock down ten men with a single strike! What am I?','Bowling ball');
insert into riddles values(23, 'I’m grown from darkness but shine with a pale light. Very round I am, and always a lady’s delight. What am I?','Pearl');
insert into riddles values(24, 'I am owned by every man, through my length differs. Their wives use me after getting married. What am I?','Lastname');
insert into riddles values(25, 'I’m white, perfect for cutting and grinding. For most animals I am a useful tool. What am I?','Teeth');
insert into riddles values(26, 'I am always around you but often forgotten. I am pure and clean most time, but occasionally rotten. What am I?','Air');
insert into riddles values(27, 'I am that only thing place today before yesterday. (one word) What am I?','Dictionary');
insert into riddles values(28, 'I may only be given but never bought. Sinners seek me but saints do not. (one word) What am I?','Forgiveness');
insert into riddles values(29, 'I will disappear every time you say my name. What am I?','Silence');
insert into riddles values(30, 'I have two bodies joined together as one. When standing still, I ran and ran. What am I?','Hourglass');
insert into riddles values(31, 'The more you take away from me, the bigger I shall get. What am I?','Hole');
insert into riddles values(32, 'I jump when I walk and sit when I stand. What am I?','Kangaroo');
insert into riddles values(33, 'I have fangs and enjoy piercing holes with a single bite. What am I?','Stapler');
insert into riddles values(34, 'I have three eyes and only one leg. Obey me or you will be sorry. What am I?','Traffic Light');
insert into riddles values(35, 'I have a straight back and sharp teeth to cut objects. What am I?','Saw');
insert into riddles values(36, 'You can catch me but cannot throw me. What am I?','Cold');
insert into riddles values(37, 'Taken from a mine and then locked up in a wooden case. Never released but used by students everyday. What am I?','Lead');
insert into riddles values(38, 'I can never be stolen from you. I am owned by everyone. Some have more, some have less. What am I?','Knowledge');
insert into riddles values(39, 'I am a mother from a family of eight. Spins around all day despite my weight. Had a ninth sibling before founding out its fake. What am I?','Earth');
insert into riddles values(40, 'The more you have me the less you see. Shine a light on me and I flea. What am I?','Darkness');
insert into riddles values(41, 'I turn everything around, but I cannot move. When you see me you see you! What am I?','Mirror');
insert into riddles values(42, 'Tear me off and scratch my head, what once red is now black. What am I?','Match');
insert into riddles values(43, 'I dance on one feet and knows only one shape. Someone with same name as me is very good with directions. What am I?','Compass');
insert into riddles values(44, 'Whoever made me don’t want me; Whoever bought me don’t need me. Whoever use me don’t know me. What am I?','Coffin');
insert into riddles values(45, 'When you take away the whole from me, there is always some left. What am I?','Wholesome');
insert into riddles values(46, 'I am a word. I become longer when the third letter is removed. What am I?','Lounger');
insert into riddles values(47, 'Born in the ocean and white as snow. When I fall back to water I disappear without a trace. What am I?','Salt');
insert into riddles values(48, 'As a state in America. I am round on both sides and high in the middle. What am I?','Ohio');
insert into riddles values(49, 'I am enjoyed by some, despised by others. Some take me for granted, some treasure me like a gift. I last forever, unless you break me first. What am I?','Marriage');
insert into riddles values(50, 'I am a king who’s good at measuring stuff. What am I?','Ruler');
insert into riddles values(51, 'I can wave my hands at you, but I never say goodbye. You are always cool when with me, even more so when I am high! What am I?','Electric Fan');
insert into riddles values(52, 'I start with “T”, ends with “T”, and within me is “T”. What am I?','Teapot');
insert into riddles values(53, 'My first half means container. Not a lot of people understand my language. What am I?','Binary');
insert into riddles values(54, 'I walk on 4 legs in the morning, 2 legs at noon, and 3 legs at night. What am I?','Human');
insert into riddles values(55, 'I start with an E, end with an E, and have a letter in me. What am I?','Envelope');
insert into riddles values(56, 'If a man carries my burden, they will get crushed to death. Though not rich, I leave silver in my track. What am I?','Snail');
insert into riddles values(57, 'I have feathers that help me fly; with head and body but I’m not alive. Very skinny and a fixed length, how far I go depends on.What am I?','Arrow');
insert into riddles values(58, 'You heard me before, and then again. Afterward I die, until you call me again. What am I?','Echo');
insert into riddles values(59, 'I am free the first time and second time, but the third time is going to cost you money. What am I?','Teeth');
insert into riddles values(60, 'I always run but never walk, often murmur but never talk, have a bed but never sleep, has a mouth but never eat. What am I?','River');
insert into riddles values(61, 'Lighter than feather and softer than silk, yet the strongest man in the world cannot hold me for more than a few minutes. What am I?','Breath');
insert into riddles values(62, 'I am the place to turn when nature calls. What am I?','Bathroom');
insert into riddles values(63, 'Soft, hairy, from door to door. I am the pet that always stays on the floor. What am I?','Carpet');
insert into riddles values(64, 'I am quick when I’m thin. I am slow when I’m fat. Wind is my worst nightmare. What am I?','Candle');
insert into riddles values(65, 'I go in dry and come out wet. The longer I stay in, the stronger my surroundings get. What am I?','Tea Bag');
insert into riddles values(66, 'If you have me, you want to share me. Once you share me, you won’t have me. What am I?','Secret');
insert into riddles values(67, 'I have a head, tail, but no arms and legs. What am I?','Coin');
insert into riddles values(68, 'I am full of holes but still holds water. What am I?','Sponge');
insert into riddles values(69, 'I sit in a corner while traveling around the world. What am I?','Stamp');
insert into riddles values(70, 'I can run but not walk. Wherever I go, thought follows close behind. What am I?','Nose');
insert into riddles values(71, 'People need me yet they give me away every day. What am I?','Money');
insert into riddles values(72, 'I make a loud noise when changing jacket, becomes bigger and delicious. What am I?','Popcorn');
insert into riddles values(73, 'I am owned by the poor, the rich does not need me. If you eat me, you will die! What am I?','Nothing');
insert into riddles values(74, 'You do not want me when you don’t have me, but when you have me you don’t want to lose me.','Lawsuit');
insert into riddles values(75, 'With a halo of water and a tongue of wood, stone as skin long I stood. What am I?','Castle');
insert into riddles values(76, 'I am a kind of coat that can only be put on when wet. What am I?','Paint');
insert into riddles values(77, 'I have a ring but no fingers. I used to stay still all the time, but nowadays I follow you around. What am I?','Telephone');
insert into riddles values(78, 'I begin and have no end. Eventually I will be the ending of all that has begun. What am I?','Death');
insert into riddles values(79, 'I must be broken before you can use me. What am I?','Egg');
insert into riddles values(80, 'I stink in living but when dead smells good. What am I?','Pig');
insert into riddles values(81, 'My rings are not worth much, but they do tell my age. What am I?','Tree');
insert into riddles values(82, 'I climb higher as I get hotter. I can never escape from my crystal cage. What am I?','Mercury');
insert into riddles values(83, 'What force and strength cannot get through, I with my unique teeth can do. What am I?','Key');
insert into riddles values(84, 'I am pronounced as one letter, written with three. I come in blue, black, brown, or grey. Reverse me and I read the same either way. What am I?','Eye');
insert into riddles values(85, 'Kings and queens may cling to power, and the jesters may have their call. I am the most common but I can rule them all. What am I?','Ace');
insert into riddles values(86, 'I take off my clothes when you put on your clothes. I put on my clothes when you take off your clothes. What am I?','Clothes Hanger');
insert into riddles values(87, 'I may be made of metal, bone, or wood and have many teeth. My bite hurts no one and the ladies love me. What am I?','Comb');
insert into riddles values(88, 'I am not a toy, though many use me for pleasure. I have a butt, but I cannot poop. What am I?','Cigarette');
insert into riddles values(89, 'I can’t go left, I can’t go right. I am forever stuck in a building over three stories high. What am I?','Elevator');
insert into riddles values(90, 'I go up when the rain comes down. What am I?','Umbrella');
insert into riddles values(91, 'If you lose me you may cause people around me to lose me too. What am I?','Temper');
insert into riddles values(92, 'I beam, I shine, I sparkle white. I’ll brighten the day with a single light. I’ll charm and enchant all. I’ll bring the best in you all. What am I?','Smile');
insert into riddles values(93, 'I am a mountain at night, meadow at day. What am I?','Bed');
insert into riddles values(94, 'I am an instrument capable of making numerous sound but cannot be touched or seen. What am I?','Voice');
insert into riddles values(95, 'Cloud is my mother, wind is my father. What am I?','Rain');
insert into riddles values(96, 'I am black, white, and read all over. What am I?','Newspaper');
insert into riddles values(97, 'I run around the streets all day. Under the bed or by the door I sit at night, never alone. My tongue hangs out, waiting to be fed during the day. What am I?','Shoe');
insert into riddles values(98, 'I am constantly overlooked by everyone but everyone has me. What am I?','Nose');
insert into riddles values(99, 'I widen my jaws when you poke two fingers in me. I especially like to devour papers. What am I?','Scissors');
insert into riddles values(100, 'I live above a star who never burns. I have 11 neighbors but they never turn. My initial are p, q, r, and sometimes s. What am I?','Seven');
insert into riddles values(101, 'I have no voice but I can teach you all there is to know. I have spines and hinges but I am not a door. Once I’ve told you all, I cannot tell you more. What am I?','Book');
insert into riddles values(102, 'I always have to work with something in my eye. What am I?','Needle');
insert into riddles values(103, 'I am bought by the yard but worn by the foot. What am I?','Carpet');
insert into riddles values(104, 'I never was but always will be. No one ever saw me but everyone knows I exist. I give people the motivation to better themselves everyday. What am I?','Tomorrow');
insert into riddles values(105, 'I go up and down at the same time. Up towards to sky and down towards the ground. What am I?','See-saw');
insert into riddles values(106, 'I am a sharp looking horse with a flaxen tail. The longer I run the shorter my tail becomes. What am I?','Needle');
insert into riddles values(107, 'I come in different colors and shapes. Some parts of me are curvy, some are straight. You can put me anywhere you like, but there is only one right place for me. What am I?','Jigsaw Puzzle');
insert into riddles values(108, 'I am alive without breath and cold as death. I am never thirsty but always drinking. What am I?','Fish');
insert into riddles values(109, 'I belong to you but others use me more often than you do. What am I?','Name');
insert into riddles values(110, 'I am rarely touched but often held, and if you are smart you’ll use me well. What am I?','Tongue');
insert into riddles values(111, 'I go around and in the house, but never touches the house. What am I?','Sun');
insert into riddles values(112, 'I am a protector. I sit on a bridge. One person can see right through me, while others wonder what I hide. What am I?','Sunglasses');
insert into riddles values(113, 'I fly away as soon as you set me loose. People around you may slowly move away once they sense my presence. What am I?','Fart');
insert into riddles values(114, 'I am an insect, half of my name is another insect. I am similar to the name of a famous band. What am I?','Beetle');
insert into riddles values(115, 'A necessity to some, a treasure to many, I’m best enjoyed among pleasant company. Some like me hot, some like me cold. Some prefer mild, some like me bold. What am I?','Coffee');
insert into riddles values(116, 'You cannot keep me until you have given me. What am I?','Your Word');
insert into riddles values(117, 'I go from house to house, a messenger small and tight. Weather it rains or snows. I sleep outside at night. What am I?','Road');
insert into riddles values(118, 'I’m really blue, but when you see me I’m red. You don’t see me too often. I’m there for you if you’re hurt, but I’m good for you. What am I?','Blood');
insert into riddles values(119, 'I am a time for gathering crops. Remove the first three letters I become an object you can wear. What am I?','Harvest');
insert into riddles values(120, 'I hold two people together but touch only one. What am I?','Wedding Ring');
insert into riddles values(121, 'You turn me over after you have traveled far. What am I?','Odometer');
insert into riddles values(122, 'Break me but I’ll continue to work, touch me and maybe I’ll stay with you forever. What am I?','Heart');
insert into riddles values(123, 'I won’t break if you throw me off from the highest building but I will break if you place me in the ocean. What am I?','Tissue');
insert into riddles values(124, 'I hide in a dark tunnel awaiting my time. I can only be released by pulling back. Once released, I may do unstoppable damage. What am I?','Bullet');
insert into riddles values(125, 'I have cities with no people, forests with no trees, and oceans with no water. What am I?','Map');
insert into riddles values(126, 'I am a nut with a hole. What am I?','Donut');
insert into riddles values(127, 'When it comes to me, you go on red and stops on green. What am I?','Watermelon');
insert into riddles values(128, 'Physicists have built devices to move me very fast. My last seven letters can be commonly found in newspapers, magazines, and journals. What am I?','Particles');
insert into riddles values(129, 'I can the same written do forward, backward, and upside down. What am I?','Noon');
insert into riddles values(130, 'I sleep when you are awake, I am awake when you fall asleep. I can fly but no feathers to aid my flight. What am I?','Bat');
insert into riddles values(131, 'I only exist when you are here. Where you never were, I can never be. What am I?','Reflection');
insert into riddles values(132, 'I can be red, blue, purple, and green. No one can reach me, not even the queen. What am I?','Rainbow');
insert into riddles values(133, 'I have six faces but not even one body connected, 21 eyes in total but cannot see. What am I?','Dice');
insert into riddles values(134, 'I have a head and a tail but my eyes can never see my tail. What am I?','Coin');
insert into riddles values(135, 'You hold my tail while I fish for you. What am I?','Net');
insert into riddles values(136, 'I am a box who holds keys but not locks. With the right combination I may unlock your soul. What am I?','Piano');
insert into riddles values(137, 'I come without being fetched at night, hides away as soon as daylight strikes. Although I may look small, I am much mightier than what you can imagine. What am I?','Star');
insert into riddles values(138, 'I do not contain flesh, feather, or scales; yet I have fingers and thumbs. What am I?','Glove');
insert into riddles values(139, 'I am all around you, but you cannot see me. I have no throat, but you can hear me. Valued during summer but despised in the winter. What am I?','Wind');
insert into riddles values(140, 'I cannot be burned in fire or drowned in water. What am I?','Ice');
insert into riddles values(141, 'I contain six letters, minus one and you got twelve. What am I?','Dozens');
insert into riddles values(142, 'Sometimes I fly as fast as the speed of light. Sometime I crawl as slow as a snail. Unknown until I am measured but you will certainly miss me when I’m gone. What am I?','Time');
insert into riddles values(143, 'I spend most of my day eating white. When I am quick enough, I get rewarded with fruit and somethings blue. In a dark room with blue walls, I run from the ghost that roam the halls. What am I?','Pac-man');
insert into riddles values(144, 'I have roots nobody sees. I am taller than trees. Up, up I go but I never grow. What am I?','Mountain');
insert into riddles values(145, 'I am a ship that can be made to ride the greatest waves. I am not built by objects, but built by minds. What am I?','Friendship');
insert into riddles values(146, 'I have a mouth on my head and eat everything. What am I?','Backpack');
insert into riddles values(147, 'I do not have eyes but I once could see. I used to have thoughts but now I’m empty. What am I?','Skull');
insert into riddles values(148, 'I get paid to shoot people, then blow them up. What am I?','Photographer');
insert into riddles values(149, 'I can be the book one can never finish reading. What am I?','Autobiography');
insert into riddles values(150, 'I am lighter than the material I am made of. You see parts of me but more of me is hidden underneath. What am I?','Iceberg');
insert into riddles values(151, 'I was not born, but I am here. I have no name, but I am given many. I was made by science and life. What am I?','Clone');
insert into riddles values(152, 'I hold two meanings. With one I may be broken, with the other I hold on. What am I?','Tie');
insert into riddles values(153, 'I love to twist and dance. Though wingless, I fly high up into the sky. What am I?','Kite');
insert into riddles values(154, 'You throw away my outside, you cook my inside. Then you eat my outside and you throw away my inside. What am I?','Corn');
insert into riddles values(155, 'I am a rock group with four members. All dead, one was assassinated. What am I?','Mt. Rushmore');
insert into riddles values(156, 'I go in hard, come out soft. Blow me hard and I’ll make a pop. What am I?','Gum');
insert into riddles values(157, 'I am a food with 5 letters. If you remove the first letter I am a form of energy. Remove two and I’m needed to live. Scramble the last 3 and you can drink me down. What am I?','Wheat');
insert into riddles values(158, 'I have a hundred legs, but cannot stand. I have a long neck, but no head. I cannot see, and I help keep your house neat and tidy. What am I?','Broom');
insert into riddles values(159, 'I cannot be bought, cannot be sold, even if I’m sometimes made of gold. What am I?','Heart');
insert into riddles values(160, 'I can be found after you remove 6 letters from BSAINXLEATEARS. What am I?','Banana');
insert into riddles values(161, 'I run up and down the stairs without moving. What am I?','Rug');
insert into riddles values(162, 'When I point up, it’s bright. When I point down, it’s dark. What am I?','Light Switch');
insert into riddles values(163, 'I ask no questions but receive a lot of answers. What am I?','Doorbell');
insert into riddles values(164, 'You use a knife to slice my head and weep beside me when I am dead. What am I?','Onion');
insert into riddles values(165, 'I am a fruit with seed on the outside. What am I?','Strawberry');
insert into riddles values(166, 'I belong to everyone. Sometimes make you happy, sometimes make you sad. I will never end until the day you do. What am I?','Thoughts');
insert into riddles values(167, 'I can wake you up in the morning but I require no electricity or winding. What am I?','Rooster');
insert into riddles values(168, 'I can generate fear and some say I come out of your ears. I am as quite as a mouse but not welcomed in the house. What am I?','Smoke');
insert into riddles values(169, 'You throw me out when you use me and take me in when you are done. What am I?','Anchor');
insert into riddles values(170, 'I drift forever with the current and flows to your everyday life. I make living easy but I am good at killing people too. What am I?','Electricity');
insert into riddles values(171, 'I have 24 keys but cannot open any locks. Sometimes loud, sometimes soft. What am I?','Music');
insert into riddles values(172, 'I am clean when I’m black, dirty when I’m white. What am I?','Chalkboard');
insert into riddles values(173, 'My first two letters say my name. My last letter asks a question. What I embrace I destroy. What am I?','Ivy');
insert into riddles values(174, 'I have wheels and flies, yet I am not an aircraft. What am I?','Garbage Truck');
insert into riddles values(175, 'I have three heads. Cut off one, I become stronger. Cut off two, I become ten. What am I?','Fox');
insert into riddles values(176, 'I contain five little items of an everyday sort. You can find all five in a tennis court. What am I?','Vowels');
insert into riddles values(177, 'I am black when you buy me, red when you use me, when I turn white. You know it’s time to throw me away. What am I?','Charcoal');
insert into riddles values(178, 'I can sizzle like bacon. I am made with an egg, I have plenty of backbone, but lack a good leg. I peel layers like onions, but still remain whole. I can be long, like a flagpole, yet fit in a hole. What am I?','Snake');
insert into riddles values(179, 'I can swim but never get wet. I can run but never get tired. I follow you everywhere but never say a word. What am I?','Shadow');
insert into riddles values(180, 'I am the beginning of the end, and the end of time and space. I am essential to creation, and I surround every place. What am I?','E');
insert into riddles values(181, 'You can throw me away, but I will always be coming back. What am I?','Boomerang');
insert into riddles values(182, 'I am in the past, never in the future. I don’t exist, but have existed. I saw what you saw, and this is what I will ever see. What am I?','Memory');
insert into riddles values(183, 'In prison I will be found, But I’ll never be in court, Unless there’s more than one. What am I?','S');
insert into riddles values(184, 'I’ve been argued on my colour. Without me you’ll die. So many attempts on your life use me, so make sure you have many of my “White” friends. What am I?','Red Blood Cell');
insert into riddles values(185, 'I see what you see, feel what you feel, and hear what you hear. I know all of your moves before you make them. I even know the moves you didn’t make. What am I?','Brain');
insert into riddles values(186, 'I am flora, not fauna. I am foliage, not trees. I am shrubbery, not grass. What am I?','Bush');
insert into riddles values(187, 'I come off a beautiful creature, which soars in the sky. I come off a peckish creature, which has a tail as mighty as the sun! I am sometimes dirty, and parents beg you not to pick me up. What am I?','Feather');
insert into riddles values(188, 'I am easy to waste and unstoppable What am I?','Time');
insert into riddles values(189, 'I am not very commonly found! Only in some rainforest! I have an odd number of toes! I’m very lazy and hang upside down! What am I?','Sloth');
insert into riddles values(190, 'I am one small little piece of paper, yet sometimes hold lots of value. I am all you need to get in to big events, but will cost you. I am an important part of travel. And if lost, you’re not coming. What am I?','Ticket');
insert into riddles values(191, 'A hole in a pole. Though I fill a hole in white, I’m used more b the day and less by the night. What am I?','Eye');
insert into riddles values(192, 'I start new then become old. Start clean but be one dirty. I usually start big then become little. What am I?','Shoes');
insert into riddles values(193, 'I can fall off a building and live, but in water I will die. What am I?','Paper');
insert into riddles values(194, 'I am what bring things together. Without me everything you see would be a total mass or debris everywhere. What am I?','Gravity');
insert into riddles values(195, 'I have been the beginning of ideas for all time, yet I am just one simple small object, the things that you can use me for can be frustrating and also I can be pretty. I have some of the most valuable thing in the world on me, yet almost everyone owns me. With me you can make anything. What am I?','Paper');
insert into riddles values(196, 'The thunder comes before the lightning, and the lightning comes before the cloud, The rain dries all the land it touches, wrapping the earth in a blood red shroud. What am I?','Volcano');
insert into riddles values(197, 'I have palms but not on hands, I offer foods from distant lands, When at my peak you’ll see me smoke, I’m famous for my friendly folk, My flowers grow and yet they lay, There’s fire where a man will play. What am I?','Hawaii');
insert into riddles values(198, 'I am beautiful, up in the sky. I am magical, yet I cannot fly. To people I bring luck, to some people, riches. The boy at my end does whatever he wishes. What am I?','Rainbow');
insert into riddles values(199, 'I may seem real but it always turns out I was never there in the first place… you only see me during a certain resting stage. What am I?','Dream');
insert into riddles values(200, 'The 8 of us go forth and back to protect our king from a foes attack. What am I?','Pawns');
insert into riddles values(251, 'I give people a huge fright, but at the end I’m sweet. I normally celebrate at night, when there’s less heat. What am I?','Halloween');
insert into riddles values(252, 'I am the ultimate killing machine, used not once but TWICE, I can be made by humans. What am I?','War');
insert into riddles values(253, 'In my life I must bare, my bloodline I must share. What am I?','Sibling');
insert into riddles values(254, 'Two in a whole and four in a pair. Six in a trio you see. Eight’s a quartet but what you must get is the name that fits just one of me. What am I?','Half');
insert into riddles values(255, 'I twist and turn and leaves a loop. What am I?','Shoelace');
insert into riddles values(256, 'I am easy to see, but no one likes looking at me. Without me, there would be no you. I can make you complain, or make you happy. But you almost always take me for granted. What am I?','Sun');
insert into riddles values(257, 'I am a type of cheese made backwards. What am I?','Edam');
insert into riddles values(258, 'Though I am dark, Adam married me. What am I?','Eve');
insert into riddles values(259, 'I am always in front of you, but you will never see me. What am I?','Future');
insert into riddles values(260, 'I will go within you, and destroy you. Only because you wanted me too. What am I?','Drugs');
insert into riddles values(261, 'I dig out tiny caves, and store gold and silver in them. I also build bridges of silver and make crowns of gold. Sooner or later everybody needs my help, yet many people afraid to let me help them. What am I?','Dentist');
insert into riddles values(262, 'To cross the water I’m the way. For water I’m above I touch it not, and truth to say, I neither swim nor move. What am I?','Bridge');
insert into riddles values(263, 'I can be simple or I can be complex. I can be found in this riddle or in everyday life. I can be shapes or even colors. What am I?','Pattern');
insert into riddles values(264, 'I am edible, pink, and a great summer food. What am I?','Peach');
insert into riddles values(265, 'I crushed on Wendy Darling. What am I?','Peter Pan');
insert into riddles values(266, 'I am a protector of the scoreboard. What am I?','Goalie');
insert into riddles values(267, 'I am needed for most animals and hardcover books. What am I?','Spine');
insert into riddles values(268, 'You used to come to me for all sorts of information and knowledge before internet was born. What am I?','Library');
insert into riddles values(269, 'I tell people to be careful when handling boxes. What am I?','Fragile');
insert into riddles values(270, 'We applaud if you perform well. What am I?','Audience');
insert into riddles values(271, 'I look like a tiny trombone. What am I?','Paperclip');
insert into riddles values(272, 'I increase head turning rate tremendously for girls at beaches. What am I?','Bikini');
insert into riddles values(273, 'I describe a toilet cleaner as well as one of Santa’s reindeer. What am I?','Comet');
insert into riddles values(274, 'I can only be played on a windy day. What am I?','Kite');
insert into riddles values(275, 'I am a candy that looks like a shepherd’s staff. What am I?','Candy Cane');
insert into riddles values(276, 'I begin your sentences. What am I?','Capital');
insert into riddles values(277, 'I am a shiny metal sheet that covers BBQ food. What am I?','Aluminum');
insert into riddles values(278, 'Deposit red liquid in me. What am I?','Blood Bank');
insert into riddles values(279, 'I don’t forget! What am I?','Elephant');
insert into riddles values(280, 'Things here are usually tagged with red stickers. What am I ?','Clearance');
insert into riddles values(281, 'I am a small paradise surrounded by dryness and heat. What am I?','Oasis');
insert into riddles values(282, 'I am a type of weapon for SCI-FI characters. What am I?','Laser');
insert into riddles values(283, 'Keep doing me to avoid lens dryness. What am I?','Blink');
insert into riddles values(284, 'I flow from the mouth of Homer when he sees doughnuts. What am I?','Drool');
insert into riddles values(285, 'I am the noise Santa’s reindeers make. What am I?','Jingle');
insert into riddles values(286, 'I store fire-breathing animals. What am I?','Dungeon');
insert into riddles values(287, 'Some people avoid me, some people count me, some people just consume me. What am I?','Calories');
insert into riddles values(288, 'I am a beverage named after a stick. What am I?','Club Soda');
insert into riddles values(289, 'Angels and pilots work with me. What am I?','Wings');
insert into riddles values(290, 'I am like thunder in your cranium. What am I?','Headache');
insert into riddles values(291, 'Better touch me before you proceed to second. What am I?','First Base');
insert into riddles values(292, 'I encourage people to run home and steal. What am I?','Baseball');
insert into riddles values(293, 'I am enjoyed with a pot and some pointy sticks. What am I?','Fondue');
insert into riddles values(294, 'I am a tool for fairies. What am I?','Magic Wand');
insert into riddles values(295, 'I hop around and deliver eggs at Easter. What am I?','Bunny');
insert into riddles values(296, 'I am a daily ritual involving using a metal tool on the body. What am I?','Shave');
insert into riddles values(297, 'I am the second L in LOL. What am I?','Loud');
insert into riddles values(298, 'I am a delicious way of representing data. What am I?','Pie Chart');
insert into riddles values(299, 'My flavors ranges from strawberry to toe. What am I?','Jam');
insert into riddles values(300, 'I am known for my natural tuxedo and marching. What am I ?','Penguin');
insert into riddles values(301, 'A popular afterlife location to send evil people. What am I?','Hell');
insert into riddles values(302, 'I am a desire to munch. What am I?','Hunger');
insert into riddles values(303, 'I keep things green and keep kids happy during summer time. What am I?','Sprinkler');
insert into riddles values(304, 'Canine children. What am I?','Puppy');
insert into riddles values(305, 'I am a way to say goodbye to your sweetheart. What am I?','Kiss');
insert into riddles values(306, 'I love spinach. What am I?','Popeye');
insert into riddles values(307, 'I have strong affection for belly buttons. What am I?','Lint');
insert into riddles values(308, 'I am a sound made by felines when petted. What am I?','Purr');
insert into riddles values(309, 'I am so delicious that I require a house to contain me. What am I?','Pancakes');
insert into riddles values(310, 'Cats and deflation tires make this noise. What am I?','Hiss');
insert into riddles values(311, 'I am a activity dogs are very good at when a ball is thrown. What am I?','Fetch');
insert into riddles values(312, 'I am very afraid of doing scary activities. What am I?','Chicken');
insert into riddles values(313, 'Found at the back of the book. What am I?','Appendix');
insert into riddles values(314, 'Hide me from your parents if you have done bad academically this year. What am I?','Report Card');
insert into riddles values(315, 'I mean goodbye for South Americans. What am I?','Adios');
insert into riddles values(316, 'I am longer than a decade and shorter than a millennium. What am I?','Century');
insert into riddles values(317, 'I help you carry your books. What am I?','Backpack');
insert into riddles values(318, 'You need thousands of me to create a digital image. What am I?','Pixel');
insert into riddles values(319, 'The Titanic is still here. What am I?','Atlantic');
insert into riddles values(320, 'I am often sold by children entrepreneurs in summer time. What am I?','Lemonade');
insert into riddles values(321, 'I am milky white and scares people. What am I?','Ghost');
insert into riddles values(322, 'Send poorly behaved children to me and let them sit here. What am I?','Corner');
insert into riddles values(323, 'I am a creature with a “tight” name. What am I?','Seal');
insert into riddles values(324, 'Four leaves I have. What am I?','Shamrock');
insert into riddles values(325, 'I am the most famous dinner. What am I?','Last Supper');
insert into riddles values(326, 'I was cracked by Indiana Jones. What am I?','Whip');
insert into riddles values(327, 'I am sometimes referred to as chips. What am I?','French Fries');
insert into riddles values(328, 'Teenage girls are pros at creating me. Learn me in classes. What am I?','Drama');
insert into riddles values(329, 'I am million people’s wakeup call. What am I?','Coffee Bean');
insert into riddles values(330, 'My teeth help me suck. What am I?','Vampire');
insert into riddles values(331, 'Island hello. What am I?','Hello');
insert into riddles values(332, 'I help boats park. What am I?','Anchor');
insert into riddles values(333, 'Santa shakes his belly like me. What am I?','Jelly');
insert into riddles values(334, 'I suck. What am I?','Vaccuum');
insert into riddles values(335, 'I am the kind of food monkey likes, and people slip on me and fall in cartoons. What am I?','Banana');
insert into riddles values(336, 'I carry you down a gental stream. What am I?','Rowboat');
insert into riddles values(337, 'I invade your home once a year… but only if you’ve been good. What am I?','Santa Claus');
insert into riddles values(338, 'I am a type of animal that hang out in the mist. What am I?','Gorilla');
insert into riddles values(339, 'An action done on mosquito bites. What am I?','Scratch');
insert into riddles values(340, 'The time between daylight and darkness when blood drinkers like to come out. What am I?','Twilight');
insert into riddles values(341, 'A piece of paper that takes most people 3 or 4 years to get. What am I?','Diploma');
insert into riddles values(342, 'I am used when you jump off a bridge for fun. What am I?','Bungee');
insert into riddles values(343, 'I am pinched by grandmas. What am I?','Cheeks');
insert into riddles values(344, 'I mirror your actions. What am I?','Copycat');
insert into riddles values(345, 'I am a busy worker who is a water mammal. What am I?','Beaver');
insert into riddles values(346, 'I am ten little beans your look at everyday. What am I?','Toes');
insert into riddles values(347, 'I travel in a gaggle. What am I?','Goose');
insert into riddles values(348, 'Light me up in backyard gatherings. What am I?','Charcoal');
insert into riddles values(349, 'I save lives on the ground and in the air. What am I?','Seatbelt');
insert into riddles values(350, 'I destroy your home from inside out. What am I?','Termite');
insert into riddles values(351, 'The only amusing part of the body. What am I?','you are');
insert into riddles values(352, 'I am the home for feathery animals. What am I?','Nest');
insert into riddles values(353, 'I am the state when a person is holding a person inside. What am I?','Pregnant');
insert into riddles values(354, 'When you are inside me, you will be encouraged to slam other cars. What am I?','Bumper Car');
insert into riddles values(355, 'I am a living following the wealthy and beautiful. What am I?','Paparazzi');
insert into riddles values(356, 'I am expelled from you orally with a sound. What am I?','Burp');
insert into riddles values(357, 'Find me on body builders or in the drink aisle. What am I?','Six Pack');
insert into riddles values(358, 'I am the best thing that can happen after a stick hits a ball. What am I?','Home Run');
insert into riddles values(359, 'I stink up your breath and fights evil vampires. What am I?','Garlic');
insert into riddles values(360, 'I am commonly abbreviated to H. What am I?','Hydrogen');
insert into riddles values(361, 'I am the minerals vital for your good health. What am I?','Vitamin');
insert into riddles values(362, 'I am owned by Old McDonald. What am I?','Farm');
insert into riddles values(363, 'I shared by goats, devils, and unicorns. What am I?','Horn');
insert into riddles values(364, 'I let water fall on you while everyone else stays dry. What am I?','Shower');
insert into riddles values(365, 'I am a caribbean shape that makes ships disappear. What am I?','Triangle');
insert into riddles values(366, 'Rub me and a genie might appear. What am I?','Lamp');
insert into riddles values(367, 'Makeup for finger tips. What am I?','Nail Polish');
insert into riddles values(368, 'I direct you from outer space. What am I?','GPS');
insert into riddles values(369, 'I transfer oxygen from the atmosphere to your blood. What am I?','Lungs');
insert into riddles values(370, 'I am the reaction after enjoying soda. What am I?','Belch');
insert into riddles values(371, 'Use me to reward good behavior. What am I?','Treat');
insert into riddles values(372, 'I cause involuntary movements in your vehicle. What am I?','Tow Truck');
insert into riddles values(373, 'I am a person who pretends to be someone else. What am I?','Imposter');
insert into riddles values(374, 'I am a lunch money thief. What am I?','Bully');
insert into riddles values(375, 'Although it sounds like I work on a transportation device, I actually work in a restaurant. What am I?','Busboy');
insert into riddles values(376, 'A move made popular b the King of Pop. What am I?','Moon Walk');
insert into riddles values(377, 'Use me if you really want to see inside someone. What am I?','X-ray');
insert into riddles values(378, 'I am a mini solar powered computer. What am I?','Calculator');
insert into riddles values(379, 'I can be entertaining until you realize some pieces have been lost. What am I?','Puzzle');
insert into riddles values(380, 'I am an activity involving pins flying int eh air. What am I?','Juggling');
insert into riddles values(381, 'Turkey day. What am I?','Thanksgiving');
insert into riddles values(382, 'There are four of us, but it seems like everyone loves spades the most. What am I?','Aces');
insert into riddles values(383, 'I am a shower that lights up the sky. What am I?','Meteor');
insert into riddles values(384, 'I carried by mad animals. What am I?','Rabies');
insert into riddles values(385, 'I am nature’s way of applauding lightning. What am I?','Thunder');
insert into riddles values(386, 'A large oasis in the desert. Come with cash and leave with none. What am I?','Las Vegas');
insert into riddles values(387, 'Sing me to a baby about to go to sleep. What am I?','Lullaby');
insert into riddles values(388, 'Digital white-out. What am I?','Delete');
insert into riddles values(389, '3 point goal. What am I?','Field Goal');
insert into riddles values(390, 'I can be heard in a court of carried with you. What am I?','Case');
insert into riddles values(391, 'Score in end zones. What am I?','Touchdown');
insert into riddles values(392, 'I am rubber you can eat! What am I?','Jelly');
insert into riddles values(393, 'Skirts for men. What am I?','Kilt');
insert into riddles values(394, 'I help engines spin and pants stay up. What am I?','Belt');
insert into riddles values(395, 'I produce wool and spit a lot. What am I?','Llama');